import { AuthContextProvider } from './Context/auth';
import './global.css';

export const metadata = {
    title: 'Eventio',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <AuthContextProvider>{children}</AuthContextProvider>
            </body>
        </html>
    );
}
