import { Inter } from 'next/font/google'
import { Logo } from '@/componens/svg/Logo';
import { AuthContextProvider } from './Context/auth';
import './global.css';

const inter = Inter({
	weight: ['400', '700'],
	subsets: ['latin'],
	display: 'swap',
  })



export const metadata = {
    title: "Eventio",
    description: 'Generated by Next.js',
	logoUrl:"@/componens/svg/Logo"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={inter.className}>
            <body >
                <AuthContextProvider>{children}</AuthContextProvider>
            </body>
        </html>
    );
}
